import crypto from "crypto";
import { CloakingConfig, TimeoutConfig } from "../config";

const BASE_URL = "https://api.anthropic.com";

/**
 * Dynamic Anthropic-Beta construction — mirrors Claude Code's utils/betas.ts
 * getAllModelBetas(). Real Claude Code sends different betas per model.
 */
function buildBetaHeader(model: string): string {
  const betas: string[] = [];

  const isHaiku = model.includes("haiku");

  // 1. Non-Haiku models always get the Claude Code beta
  if (!isHaiku) {
    betas.push("claude-code-20250219");
  }

  // 2. OAuth users always get this
  betas.push("oauth-2025-04-20");

  // 3. Interleaved thinking — all models that support ISP
  if (!isHaiku) {
    betas.push("interleaved-thinking-2025-05-14");
  }

  // 4. Context management — 1P, claude-4+ models
  betas.push("context-management-2025-06-27");

  // 5. Prompt caching scope — always on 1P
  betas.push("prompt-caching-scope-2026-01-05");

  return betas.join(",");
}

/**
 * Stainless SDK headers — the @anthropic-ai/sdk package (generated by
 * Stainless) injects these automatically on every request. Claude Code
 * never sets them explicitly; the SDK does.  We replicate them here since
 * we bypass the SDK and use raw fetch().
 *
 * Values should match the SDK version that the target Claude Code release
 * bundles. "0.74.0" corresponds to CLI ≈ 2.1.88.
 */
function getStainlessArch(): string {
  const arch = process.arch;
  if (arch === "arm64") return "arm64";
  if (arch === "x64") return "x64";
  return "x86";
}

function getStainlessOs(): string {
  const platform = process.platform;
  if (platform === "darwin") return "MacOS";
  if (platform === "win32") return "Windows";
  if (platform === "freebsd") return "FreeBSD";
  return "Linux";
}

/**
 * Per-API-key session IDs — mimics Claude Code's bootstrap/state.ts.
 *
 * Real Claude Code: one randomUUID() per CLI process, reused for every API
 * call in that session, regenerated on /clear.
 *
 * auth2api is a long-running server, so a single global session ID would look
 * like one CLI session that never closes. Instead we maintain one session ID
 * per client API key (≈ one "CLI process" per user). Each session ID expires
 * after SESSION_TTL_MS of inactivity so repeated use still looks like a human
 * reopening their terminal periodically.
 */
const sessionMap = new Map<string, string>();

export function getSessionId(apiKeyHash: string): string {
  const existing = sessionMap.get(apiKeyHash);
  if (existing) return existing;
  const id = crypto.randomUUID();
  sessionMap.set(apiKeyHash, id);
  return id;
}

/** Force-rotate session for a given API key. */
export function resetSessionId(apiKeyHash: string): void {
  sessionMap.delete(apiKeyHash);
}

/** Default values */
const DEFAULT_CLI_VERSION = "2.1.88";
const DEFAULT_ENTRYPOINT = "cli";

function buildHeaders(
  accessToken: string,
  stream: boolean,
  timeoutMs: number,
  model: string,
  cloaking: CloakingConfig,
  apiKeyHash?: string,
  extraHeaders?: Record<string, string>,
): Record<string, string> {
  const cliVersion = cloaking["cli-version"] || DEFAULT_CLI_VERSION;
  const entrypoint = cloaking.entrypoint || DEFAULT_ENTRYPOINT;
  const sessionId = getSessionId(apiKeyHash || "default");

  // Header casing from mitmproxy capture of real Claude Code CLI:
  // - anthropic-*, x-app, x-client-request-id: lowercase
  // - Everything else: capitalized
  const headers: Record<string, string> = {
    // Capitalized headers
    "Content-Type": "application/json",
    Authorization: `Bearer ${accessToken}`,
    "User-Agent": `claude-cli/${cliVersion} (external, ${entrypoint})`,
    "X-Claude-Code-Session-Id": sessionId,
    "X-Stainless-Lang": "js",
    "X-Stainless-Package-Version": "0.74.0",
    "X-Stainless-Runtime": "node",
    "X-Stainless-Runtime-Version": "v22.13.0",
    "X-Stainless-Arch": getStainlessArch(),
    "X-Stainless-Os": getStainlessOs(),
    "X-Stainless-Timeout": String(Math.max(1, Math.ceil(timeoutMs / 1000))),
    "X-Stainless-Retry-Count": "0",
    Accept: stream ? "text/event-stream" : "application/json",
    // Lowercase headers
    "anthropic-beta": buildBetaHeader(model),
    "anthropic-dangerous-direct-browser-access": "true",
    "anthropic-version": "2023-06-01",
    "x-app": "cli",
    "x-client-request-id": crypto.randomUUID(),
  };

  // Override with extra headers (e.g. anthropic-* from claude-cli clients)
  if (extraHeaders) {
    Object.assign(headers, extraHeaders);
  }

  return headers;
}

export async function callClaudeAPI(
  accessToken: string,
  body: any,
  stream: boolean,
  timeouts: TimeoutConfig,
  cloaking: CloakingConfig,
  apiKeyHash?: string,
  extraHeaders?: Record<string, string>,
): Promise<Response> {
  const url = `${BASE_URL}/v1/messages?beta=true`;
  const model = body.model || "claude-sonnet-4-6";
  const timeoutMs = stream
    ? timeouts["stream-messages-ms"]
    : timeouts["messages-ms"];
  const headers = buildHeaders(
    accessToken,
    stream,
    timeoutMs,
    model,
    cloaking,
    apiKeyHash,
    extraHeaders,
  );

  const response = await fetch(url, {
    method: "POST",
    headers,
    body: JSON.stringify(body),
    signal: AbortSignal.timeout(timeoutMs),
  });

  // Log error details if request failed
  if (!response.ok) {
    const errorBody = await response.text();
    console.error("=".repeat(80));
    console.error("CLAUDE API REQUEST FAILED");
    console.error("=".repeat(80));
    console.error("Status:", response.status, response.statusText);
    console.error("URL:", url);
    console.error("\n--- Request Headers ---");
    console.error(JSON.stringify(headers, null, 2));
    console.error("\n--- Request Body ---");
    console.error(JSON.stringify(body, null, 2));
    console.error("\n--- Response Body ---");
    console.error(errorBody);
    console.error("=".repeat(80));
  }

  return response;
}

export async function callClaudeCountTokens(
  accessToken: string,
  body: any,
  timeouts: TimeoutConfig,
  cloaking: CloakingConfig,
  apiKeyHash?: string,
): Promise<Response> {
  const url = `${BASE_URL}/v1/messages/count_tokens?beta=true`;
  const rawModel = body.model || "claude-sonnet-4-6";
  const headers = buildHeaders(
    accessToken,
    false,
    timeouts["count-tokens-ms"],
    rawModel,
    cloaking,
    apiKeyHash,
  );

  const response = await fetch(url, {
    method: "POST",
    headers,
    body: JSON.stringify(body),
    signal: AbortSignal.timeout(timeouts["count-tokens-ms"]),
  });

  // Log error details if request failed
  if (!response.ok) {
    const errorBody = await response.text();
    console.error("=".repeat(80));
    console.error("CLAUDE COUNT_TOKENS API REQUEST FAILED");
    console.error("=".repeat(80));
    console.error("Status:", response.status, response.statusText);
    console.error("URL:", url);
    console.error("\n--- Request Headers ---");
    console.error(JSON.stringify(headers, null, 2));
    console.error("\n--- Request Body ---");
    console.error(JSON.stringify(body, null, 2));
    console.error("\n--- Response Body ---");
    console.error(errorBody);
    console.error("=".repeat(80));
  }

  return response;
}
